

		/* PRACTICE SESSION 6 */

            -- 1. Converting ActPendInsur_staging table to clean, optimized data types
	SELECT  
        CAST(DOCKET_NUMBER AS varchar(9)) AS DOCKET_NUMBER,
        CAST(DOT_NUMBER AS char(8)) AS DOT_NUMBER,
        CAST(ins_form_code AS char(3)) AS ins_form_code,
        CAST(ins_type_desc AS varchar(13)) AS ins_type_desc,
        CAST(name_company AS varchar(45)) AS name_company,
        CAST(policy_no AS varchar(25)) AS policy_no,
        TRY_CONVERT(date, trans_date, 101) AS trans_date,
        TRY_CONVERT(int, underl_lim_amount) AS underl_lim_amount,
        TRY_CONVERT(int, max_cov_amount) AS max_cov_amount,
        TRY_CONVERT(date, effective_date, 101) AS effective_date,
        TRY_CONVERT(date, cancl_effective_date, 101) AS cancl_effective_date
    INTO dbo.ActPendInsur_clean
    FROM dbo.ActPendInsur_staging;

        -- Verify row counts match between staging and clean tables
    SELECT
    (SELECT COUNT(*) FROM dbo.ActPendInsur_staging) AS staging_rows,
    (SELECT COUNT(*) FROM dbo.ActPendInsur_clean) AS clean_rows;

        -- Verify column data types.
    SELECT 
        TABLE_NAME
        COLUMN_NAME, 
        DATA_TYPE, 
        CHARACTER_MAXIMUM_LENGTH
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME IN ('ActPendInsur_clean', 'ActPendInsur_staging')
    ORDER BY TABLE_NAME, ORDINAL_POSITION;

        -- Compare row counts and table sizes
    SELECT 
        OBJECT_NAME(object_id) AS table_name,
       SUM(row_count) AS [rows],
       CAST(SUM(used_page_count)*8.0/1024 AS decimal(12,2)) AS used_mb
    FROM sys.dm_db_partition_stats
    WHERE OBJECT_NAME(object_id) IN ('ActPendInsur_staging', 'ActPendInsur_clean')
    GROUP BY object_id
    ORDER BY used_mb;

        -- 2. Converting Company_Census_staging table to clean, optimized data types
  
SELECT
    TRY_CONVERT(smalldatetime,
        SUBSTRING(NULLIF(MCS150_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(MCS150_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(MCS150_DATE,''),7,2)+' '+
        SUBSTRING(NULLIF(MCS150_DATE,''),10,2)+':'+SUBSTRING(NULLIF(MCS150_DATE,''),12,2)
    ) AS MCS150_DATE,
    TRY_CONVERT(date, NULLIF(ADD_DATE,'')) AS ADD_DATE,
    CAST(STATUS_CODE AS char(1)) AS STATUS_CODE,
    TRY_CONVERT(int, NULLIF(DOT_NUMBER,'')) AS DOT_NUMBER,
    CAST(DUN_BRADSTREET_NO AS varchar(9)) AS DUN_BRADSTREET_NO,
    TRY_CONVERT(tinyint, NULLIF(PHY_OMC_REGION,'')) AS PHY_OMC_REGION,
    CAST(SAFETY_INV_TERR AS varchar(2)) AS SAFETY_INV_TERR,
    CAST(CARRIER_OPERATION AS char(1)) AS CARRIER_OPERATION,
    TRY_CONVERT(tinyint, NULLIF(BUSINESS_ORG_ID,'')) AS BUSINESS_ORG_ID,
    TRY_CONVERT(bigint, NULLIF(MCS150_MILEAGE,'')) AS MCS150_MILEAGE,
    TRY_CONVERT(smallint, NULLIF(MCS150_MILEAGE_YEAR,'')) AS MCS150_MILEAGE_YEAR,
    TRY_CONVERT(bigint, NULLIF(MCS151_MILEAGE,'')) AS MCS151_MILEAGE,
    TRY_CONVERT(int, NULLIF(TOTAL_CARS,'')) AS TOTAL_CARS,
    CAST(MCS150_UPDATE_CODE_ID AS char(1)) AS MCS150_UPDATE_CODE_ID,
    CAST(PRIOR_REVOKE_FLAG AS char(1)) AS PRIOR_REVOKE_FLAG,
    TRY_CONVERT(int, NULLIF(PRIOR_REVOKE_DOT_NUMBER,'')) AS PRIOR_REVOKE_DOT_NUMBER,
    CAST(PHONE AS varchar(13)) AS PHONE,
    CAST(FAX AS varchar(13)) AS FAX,
    CAST(CELL_PHONE AS varchar(13)) AS CELL_PHONE,
    CAST(COMPANY_OFFICER_1 AS varchar(120)) AS COMPANY_OFFICER_1,
    CAST(COMPANY_OFFICER_2 AS varchar(120)) AS COMPANY_OFFICER_2,
    CAST(BUSINESS_ORG_DESC AS varchar(11)) AS BUSINESS_ORG_DESC,
    TRY_CONVERT(int, NULLIF(TRUCK_UNITS,'')) AS TRUCK_UNITS,
    TRY_CONVERT(int, NULLIF(POWER_UNITS,'')) AS POWER_UNITS,
    TRY_CONVERT(int, NULLIF(BUS_UNITS,'')) AS BUS_UNITS,
    CAST(FLEETSIZE AS char(1)) AS FLEETSIZE,
    TRY_CONVERT(int, NULLIF(REVIEW_ID,'')) AS REVIEW_ID,
    TRY_CONVERT(decimal(6,3), NULLIF(RECORDABLE_CRASH_RATE,'')) AS RECORDABLE_CRASH_RATE,
    CAST(MAIL_NATIONALITY_INDICATOR AS char(1)) AS MAIL_NATIONALITY_INDICATOR,
    CAST(PHY_NATIONALITY_INDICATOR AS char(1)) AS PHY_NATIONALITY_INDICATOR,
    CAST(PHY_BARRIO AS varchar(50)) AS PHY_BARRIO,
    CAST(MAIL_BARRIO AS varchar(50)) AS MAIL_BARRIO,
    CAST(CARSHIP AS char(1)) AS CARSHIP,
    CAST(DOCKET1PREFIX AS char(2)) AS DOCKET1PREFIX,
    TRY_CONVERT(int, NULLIF(DOCKET1,'')) AS DOCKET1,
    CAST(DOCKET2PREFIX AS char(2)) AS DOCKET2PREFIX,
    TRY_CONVERT(int, NULLIF(DOCKET2,'')) AS DOCKET2,
    CAST(DOCKET3PREFIX AS char(2)) AS DOCKET3PREFIX,
    TRY_CONVERT(int, NULLIF(DOCKET3,'')) AS DOCKET3,
    CAST(POINTNUM AS char(1)) AS POINTNUM,
    TRY_CONVERT(int, NULLIF(TOTAL_INTRASTATE_DRIVERS,'')) AS TOTAL_INTRASTATE_DRIVERS,
    TRY_CONVERT(tinyint, NULLIF(MCSIPSTEP,'')) AS MCSIPSTEP,
    TRY_CONVERT(date, NULLIF(MCSIPDATE,'')) AS MCSIPDATE,
    CAST(HM_Ind AS char(1)) AS HM_Ind,
    TRY_CONVERT(int, NULLIF(INTERSTATE_BEYOND_100_MILES,'')) AS INTERSTATE_BEYOND_100_MILES,
    TRY_CONVERT(int, NULLIF(INTERSTATE_WITHIN_100_MILES,'')) AS INTERSTATE_WITHIN_100_MILES,
    TRY_CONVERT(int, NULLIF(INTRASTATE_BEYOND_100_MILES,'')) AS INTRASTATE_BEYOND_100_MILES,
    TRY_CONVERT(int, NULLIF(INTRASTATE_WITHIN_100_MILES,'')) AS INTRASTATE_WITHIN_100_MILES,
    TRY_CONVERT(int, NULLIF(TOTAL_CDL,'')) AS TOTAL_CDL,
    TRY_CONVERT(int, NULLIF(TOTAL_DRIVERS,'')) AS TOTAL_DRIVERS,
    TRY_CONVERT(int, NULLIF(AVG_DRIVERS_LEASED_PER_MONTH,'')) AS AVG_DRIVERS_LEASED_PER_MONTH,
    CAST(CLASSDEF AS varchar(20)) AS CLASSDEF,
    CAST(LEGAL_NAME AS varchar(120)) AS LEGAL_NAME,
    CAST(DBA_NAME AS varchar(120)) AS DBA_NAME,
    CAST(PHY_STREET AS varchar(50)) AS PHY_STREET,
    CAST(PHY_CITY AS varchar(25)) AS PHY_CITY,
    CAST(PHY_COUNTRY AS char(2)) AS PHY_COUNTRY,
    CAST(PHY_STATE AS char(2)) AS PHY_STATE,
    CAST(PHY_ZIP AS varchar(10)) AS PHY_ZIP,
    CAST(PHY_CNTY AS char(3)) AS PHY_CNTY,
    CAST(CARRIER_MAILING_STREET AS varchar(50)) AS CARRIER_MAILING_STREET,
    CAST(CARRIER_MAILING_STATE AS char(2)) AS CARRIER_MAILING_STATE,
    CAST(CARRIER_MAILING_CITY AS varchar(25)) AS CARRIER_MAILING_CITY,
    CAST(CARRIER_MAILING_COUNTRY AS char(2)) AS CARRIER_MAILING_COUNTRY,
    CAST(CARRIER_MAILING_ZIP AS varchar(10)) AS CARRIER_MAILING_ZIP,
    CAST(CARRIER_MAILING_CNTY AS char(3)) AS CARRIER_MAILING_CNTY,
    TRY_CONVERT(date, NULLIF(CARRIER_MAILING_UND_DATE,'')) AS CARRIER_MAILING_UND_DATE,
    TRY_CONVERT(int, NULLIF(DRIVER_INTER_TOTAL,'')) AS DRIVER_INTER_TOTAL,
    CAST(EMAIL_ADDRESS AS varchar(80)) AS EMAIL_ADDRESS,
    CAST(REVIEW_TYPE AS char(1)) AS REVIEW_TYPE,
    TRY_CONVERT(date, NULLIF(REVIEW_DATE,'')) AS REVIEW_DATE,
    CAST(SAFETY_RATING AS char(1)) AS SAFETY_RATING,
    TRY_CONVERT(date, NULLIF(SAFETY_RATING_DATE,'')) AS SAFETY_RATING_DATE,
    CAST(UNDELIV_PHY AS char(1)) AS UNDELIV_PHY,
    CAST(CRGO_GENFREIGHT AS char(1)) AS CRGO_GENFREIGHT,
    CAST(CRGO_HOUSEHOLD AS char(1)) AS CRGO_HOUSEHOLD,
    CAST(CRGO_METALSHEET AS char(1)) AS CRGO_METALSHEET,
    CAST(CRGO_MOTOVEH AS char(1)) AS CRGO_MOTOVEH,
    CAST(CRGO_DRIVETOW AS char(1)) AS CRGO_DRIVETOW,
    CAST(CRGO_LOGPOLE AS char(1)) AS CRGO_LOGPOLE,
    CAST(CRGO_BLDGMAT AS char(1)) AS CRGO_BLDGMAT,
    CAST(CRGO_MOBILEHOME AS char(1)) AS CRGO_MOBILEHOME,
    CAST(CRGO_MACHLRG AS char(1)) AS CRGO_MACHLRG,
    CAST(CRGO_PRODUCE AS char(1)) AS CRGO_PRODUCE,
    CAST(CRGO_LIQGAS AS char(1)) AS CRGO_LIQGAS,
    CAST(CRGO_INTERMODAL AS char(1)) AS CRGO_INTERMODAL,
    CAST(CRGO_PASSENGERS AS char(1)) AS CRGO_PASSENGERS,
    CAST(CRGO_OILFIELD AS char(1)) AS CRGO_OILFIELD,
    CAST(CRGO_LIVESTOCK AS char(1)) AS CRGO_LIVESTOCK,
    CAST(CRGO_GRAINFEED AS char(1)) AS CRGO_GRAINFEED,
    CAST(CRGO_COALCOKE AS char(1)) AS CRGO_COALCOKE,
    CAST(CRGO_MEAT AS char(1)) AS CRGO_MEAT,
    CAST(CRGO_GARBAGE AS char(1)) AS CRGO_GARBAGE,
    CAST(CRGO_USMAIL AS char(1)) AS CRGO_USMAIL,
    CAST(CRGO_CHEM AS char(1)) AS CRGO_CHEM,
    CAST(CRGO_DRYBULK AS char(1)) AS CRGO_DRYBULK,
    CAST(CRGO_COLDFOOD AS char(1)) AS CRGO_COLDFOOD,
    CAST(CRGO_BEVERAGES AS char(1)) AS CRGO_BEVERAGES,
    CAST(CRGO_PAPERPROD AS char(1)) AS CRGO_PAPERPROD,
    CAST(CRGO_UTILITY AS char(1)) AS CRGO_UTILITY,
    CAST(CRGO_FARMSUPP AS char(1)) AS CRGO_FARMSUPP,
    CAST(CRGO_CONSTRUCT AS char(1)) AS CRGO_CONSTRUCT,
    CAST(CRGO_WATERWELL AS char(1)) AS CRGO_WATERWELL,
    CAST(CRGO_CARGOOTHR AS char(1)) AS CRGO_CARGOOTHR,
    CAST(CRGO_CARGOOTHR_DESC AS varchar(50)) AS CRGO_CARGOOTHR_DESC,
    TRY_CONVERT(int, NULLIF(OWNTRUCK,'')) AS OWNTRUCK,
    TRY_CONVERT(int, NULLIF(OWNTRACT,'')) AS OWNTRACT,
    TRY_CONVERT(int, NULLIF(OWNTRAIL,'')) AS OWNTRAIL,
    TRY_CONVERT(int, NULLIF(OWNCOACH,'')) AS OWNCOACH,
    TRY_CONVERT(int, NULLIF(OWNSCHOOL_1_8,'')) AS OWNSCHOOL_1_8,
    TRY_CONVERT(int, NULLIF(OWNSCHOOL_9_15,'')) AS OWNSCHOOL_9_15,
    TRY_CONVERT(int, NULLIF(OWNSCHOOL_16,'')) AS OWNSCHOOL_16,
    TRY_CONVERT(int, NULLIF(OWNBUS_16,'')) AS OWNBUS_16,
    TRY_CONVERT(int, NULLIF(OWNVAN_1_8,'')) AS OWNVAN_1_8,
    TRY_CONVERT(int, NULLIF(OWNVAN_9_15,'')) AS OWNVAN_9_15,
    TRY_CONVERT(int, NULLIF(OWNLIMO_1_8,'')) AS OWNLIMO_1_8,
    TRY_CONVERT(int, NULLIF(OWNLIMO_9_15,'')) AS OWNLIMO_9_15,
    TRY_CONVERT(int, NULLIF(OWNLIMO_16,'')) AS OWNLIMO_16,
    TRY_CONVERT(int, NULLIF(TRMTRUCK,'')) AS TRMTRUCK,
    TRY_CONVERT(int, NULLIF(TRMTRACT,'')) AS TRMTRACT,
    TRY_CONVERT(int, NULLIF(TRMTRAIL,'')) AS TRMTRAIL,
    TRY_CONVERT(int, NULLIF(TRMCOACH,'')) AS TRMCOACH,
    TRY_CONVERT(int, NULLIF(TRMSCHOOL_1_8,'')) AS TRMSCHOOL_1_8,
    TRY_CONVERT(int, NULLIF(TRMSCHOOL_9_15,'')) AS TRMSCHOOL_9_15,
    TRY_CONVERT(int, NULLIF(TRMSCHOOL_16,'')) AS TRMSCHOOL_16,
    TRY_CONVERT(int, NULLIF(TRMBUS_16,'')) AS TRMBUS_16,
    TRY_CONVERT(int, NULLIF(TRMVAN_1_8,'')) AS TRMVAN_1_8,
    TRY_CONVERT(int, NULLIF(TRMVAN_9_15,'')) AS TRMVAN_9_15,
    TRY_CONVERT(int, NULLIF(TRMLIMO_1_8,'')) AS TRMLIMO_1_8,
    TRY_CONVERT(int, NULLIF(TRMLIMO_9_15,'')) AS TRMLIMO_9_15,
    TRY_CONVERT(int, NULLIF(TRMLIMO_16,'')) AS TRMLIMO_16,
    TRY_CONVERT(int, NULLIF(TRPTRUCK,'')) AS TRPTRUCK,
    TRY_CONVERT(int, NULLIF(TRPTRACT,'')) AS TRPTRACT,
    TRY_CONVERT(int, NULLIF(TRPTRAIL,'')) AS TRPTRAIL,
    TRY_CONVERT(int, NULLIF(TRPCOACH,'')) AS TRPCOACH,
    TRY_CONVERT(int, NULLIF(TRPSCHOOL_1_8,'')) AS TRPSCHOOL_1_8,
    TRY_CONVERT(int, NULLIF(TRPSCHOOL_9_15,'')) AS TRPSCHOOL_9_15,
    TRY_CONVERT(int, NULLIF(TRPSCHOOL_16,'')) AS TRPSCHOOL_16,
    TRY_CONVERT(int, NULLIF(TRPBUS_16,'')) AS TRPBUS_16,
    TRY_CONVERT(int, NULLIF(TRPVAN_1_8,'')) AS TRPVAN_1_8,
    TRY_CONVERT(int, NULLIF(TRPVAN_9_15,'')) AS TRPVAN_9_15,
    TRY_CONVERT(int, NULLIF(TRPLIMO_1_8,'')) AS TRPLIMO_1_8,
    TRY_CONVERT(int, NULLIF(TRPLIMO_9_15,'')) AS TRPLIMO_9_15,
    TRY_CONVERT(int, NULLIF(TRPLIMO_16,'')) AS TRPLIMO_16,
    CAST(DOCKET1_STATUS_CODE AS char(1)) AS DOCKET1_STATUS_CODE,
    CAST(DOCKET2_STATUS_CODE AS char(1)) AS DOCKET2_STATUS_CODE,
    CAST(DOCKET3_STATUS_CODE AS char(1)) AS DOCKET3_STATUS_CODE
INTO dbo.Company_Census_clean
FROM dbo.Company_Census_staging;

            -- Verify row counts match between staging and clean tables
    SELECT
        (SELECT COUNT(*) FROM dbo.Company_Census_staging) AS staging_rows,
        (SELECT COUNT(*) FROM dbo.Company_Census_clean) AS clean_rows;

            -- Verify column data types.
    SELECT 
        TABLE_NAME
        COLUMN_NAME, 
        DATA_TYPE, 
        CHARACTER_MAXIMUM_LENGTH
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME IN ('Company_Census_staging', 'Company_Census_clean')
    ORDER BY TABLE_NAME, ORDINAL_POSITION;

        -- Compare row counts and table sizes
    SELECT OBJECT_NAME(object_id) AS table_name,
       SUM(row_count) AS [rows],
       CAST(SUM(used_page_count)*8.0/1024 AS decimal(12,2)) AS used_mb
    FROM sys.dm_db_partition_stats
    WHERE OBJECT_NAME(object_id) IN ('Company_Census_staging', 'Company_Census_clean')
    GROUP BY object_id
    ORDER BY used_mb;


            -- 3. Converting Vehicle_Inspection_staging table to clean, optimized data types.
    SELECT
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(CHANGE_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(CHANGE_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(CHANGE_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(CHANGE_DATE,''),10,2)+':'+SUBSTRING(NULLIF(CHANGE_DATE,''),12,2)) AS CHANGE_DATE,
    TRY_CONVERT(int, NULLIF(INSPECTION_ID,'')) AS INSPECTION_ID,
    TRY_CONVERT(int, NULLIF(DOT_NUMBER,'')) AS DOT_NUMBER,
    CAST(REPORT_STATE AS char(2)) AS REPORT_STATE,
    CAST(REPORT_NUMBER AS varchar(10)) AS REPORT_NUMBER,
    TRY_CONVERT(date, NULLIF(INSP_DATE,'')) AS INSP_DATE,
    CAST(INSP_START_TIME AS char(4)) AS INSP_START_TIME,
    CAST(INSP_END_TIME AS char(4)) AS INSP_END_TIME,
    TRY_CONVERT(date, NULLIF(REGISTRATION_DATE,'')) AS REGISTRATION_DATE,
    CAST(REGION AS char(2)) AS REGION,
    CAST(CI_STATUS_CODE AS char(1)) AS CI_STATUS_CODE,
    CAST(LOCATION AS varchar(6)) AS LOCATION,
    CAST(LOCATION_DESC AS varchar(30)) AS LOCATION_DESC,
    CAST(COUNTY_CODE_STATE AS char(2)) AS COUNTY_CODE_STATE,
    CAST(COUNTY_CODE AS char(3)) AS COUNTY_CODE,
    TRY_CONVERT(tinyint, NULLIF(INSP_LEVEL_ID,'')) AS INSP_LEVEL_ID,
    CAST(SERVICE_CENTER AS char(2)) AS SERVICE_CENTER,
    TRY_CONVERT(tinyint, NULLIF(CENSUS_SOURCE_ID,'')) AS CENSUS_SOURCE_ID,
    CAST(INSP_FACILITY AS char(1)) AS INSP_FACILITY,
    CAST(SHIPPER_NAME AS varchar(120)) AS SHIPPER_NAME,
    CAST(SHIPPING_PAPER_NUMBER AS varchar(15)) AS SHIPPING_PAPER_NUMBER,
    CAST(CARGO_TANK AS varchar(3)) AS CARGO_TANK,
    CAST(HAZMAT_PLACARD_REQ AS char(1)) AS HAZMAT_PLACARD_REQ,
    CAST(SNET_VERSION_NUMBER AS varchar(8)) AS SNET_VERSION_NUMBER,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(SNET_SEARCH_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(SNET_SEARCH_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(SNET_SEARCH_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(SNET_SEARCH_DATE,''),10,2)+':'+SUBSTRING(NULLIF(SNET_SEARCH_DATE,''),12,2)) AS SNET_SEARCH_DATE,
    CAST(ALCOHOL_CONTROL_SUB AS char(1)) AS ALCOHOL_CONTROL_SUB,
    CAST(DRUG_INTRDCTN_SEARCH AS char(1)) AS DRUG_INTRDCTN_SEARCH,
    TRY_CONVERT(tinyint, NULLIF(DRUG_INTRDCTN_ARRESTS,'')) AS DRUG_INTRDCTN_ARRESTS,
    CAST(SIZE_WEIGHT_ENF AS char(1)) AS SIZE_WEIGHT_ENF,
    CAST(TRAFFIC_ENF AS char(1)) AS TRAFFIC_ENF,
    CAST(LOCAL_ENF_JURISDICTION AS char(1)) AS LOCAL_ENF_JURISDICTION,
    CAST(PEN_CEN_MATCH AS char(1)) AS PEN_CEN_MATCH,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(FINAL_STATUS_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(FINAL_STATUS_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(FINAL_STATUS_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(FINAL_STATUS_DATE,''),10,2)+':'+SUBSTRING(NULLIF(FINAL_STATUS_DATE,''),12,2)) AS FINAL_STATUS_DATE,
    CAST(POST_ACC_IND AS char(1)) AS POST_ACC_IND,
    TRY_CONVERT(int, NULLIF(GROSS_COMB_VEH_WT,'')) AS GROSS_COMB_VEH_WT,
    TRY_CONVERT(tinyint, NULLIF(VIOL_TOTAL,'')) AS VIOL_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(OOS_TOTAL,'')) AS OOS_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(DRIVER_VIOL_TOTAL,'')) AS DRIVER_VIOL_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(DRIVER_OOS_TOTAL,'')) AS DRIVER_OOS_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(VEHICLE_VIOL_TOTAL,'')) AS VEHICLE_VIOL_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(VEHICLE_OOS_TOTAL,'')) AS VEHICLE_OOS_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(HAZMAT_VIOL_TOTAL,'')) AS HAZMAT_VIOL_TOTAL,
    TRY_CONVERT(tinyint, NULLIF(HAZMAT_OOS_TOTAL,'')) AS HAZMAT_OOS_TOTAL,
    TRY_CONVERT(int, NULLIF(SNET_SEQUENCE_ID,'')) AS SNET_SEQUENCE_ID,
    CAST(TRANSACTION_CODE AS char(1)) AS TRANSACTION_CODE,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(TRANSACTION_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(TRANSACTION_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(TRANSACTION_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(TRANSACTION_DATE,''),10,2)+':'+SUBSTRING(NULLIF(TRANSACTION_DATE,''),12,2)) AS TRANSACTION_DATE,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(UPLOAD_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(UPLOAD_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(UPLOAD_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(UPLOAD_DATE,''),10,2)+':'+SUBSTRING(NULLIF(UPLOAD_DATE,''),12,2)) AS UPLOAD_DATE,
    CAST(UPLOAD_FIRST_BYTE AS char(1)) AS UPLOAD_FIRST_BYTE,
    CAST(UPLOAD_DOT_NUMBER AS char(8)) AS UPLOAD_DOT_NUMBER,
    CAST(UPLOAD_SEARCH_INDICATOR AS char(1)) AS UPLOAD_SEARCH_INDICATOR,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(CENSUS_SEARCH_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(CENSUS_SEARCH_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(CENSUS_SEARCH_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(CENSUS_SEARCH_DATE,''),10,2)+':'+SUBSTRING(NULLIF(CENSUS_SEARCH_DATE,''),12,2)) AS CENSUS_SEARCH_DATE,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(SNET_INPUT_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(SNET_INPUT_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(SNET_INPUT_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(SNET_INPUT_DATE,''),10,2)+':'+SUBSTRING(NULLIF(SNET_INPUT_DATE,''),12,2)) AS SNET_INPUT_DATE,
    CAST(SOURCE_OFFICE AS varchar(7)) AS SOURCE_OFFICE,
    TRY_CONVERT(smalldatetime,
    SUBSTRING(NULLIF(MCMIS_ADD_DATE,''),1,4)+'-'+SUBSTRING(NULLIF(MCMIS_ADD_DATE,''),5,2)+'-'+SUBSTRING(NULLIF(MCMIS_ADD_DATE,''),7,2)+' '+
    SUBSTRING(NULLIF(MCMIS_ADD_DATE,''),10,2)+':'+SUBSTRING(NULLIF(MCMIS_ADD_DATE,''),12,2)) AS MCMIS_ADD_DATE,
    CAST(INSP_CARRIER_NAME AS varchar(120)) AS INSP_CARRIER_NAME,
    CAST(INSP_CARRIER_STREET AS varchar(50)) AS INSP_CARRIER_STREET,
    CAST(INSP_CARRIER_CITY AS varchar(25)) AS INSP_CARRIER_CITY,
    CAST(INSP_CARRIER_STATE AS char(2)) AS INSP_CARRIER_STATE,
    CAST(INSP_CARRIER_ZIP_CODE AS varchar(10)) AS INSP_CARRIER_ZIP_CODE,
    CAST(INSP_COLONIA AS varchar(30)) AS INSP_COLONIA,
    TRY_CONVERT(int, NULLIF(DOCKET_NUMBER,'')) AS DOCKET_NUMBER,
    CAST(INSP_INTERSTATE AS char(1)) AS INSP_INTERSTATE,
    CAST(INSP_CARRIER_STATE_ID AS varchar(12)) AS INSP_CARRIER_STATE_ID
INTO dbo.Vehicle_Inspection_clean
FROM dbo.Vehicle_Inspection_staging;
      

      -- Verify row counts match between staging and clean tables
    SELECT
        (SELECT COUNT(*) FROM dbo.Vehicle_Inspection_staging) AS staging_rows,
        (SELECT COUNT(*) FROM dbo.Vehicle_Inspection_clean) AS clean_rows;

            -- Verify column data types.
    SELECT 
        TABLE_NAME
        COLUMN_NAME, 
        DATA_TYPE, 
        CHARACTER_MAXIMUM_LENGTH
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME IN ('Vehicle_Inspection_staging', 'Vehicle_Inspection_clean')
    ORDER BY TABLE_NAME, ORDINAL_POSITION;

        -- Compare row counts and table sizes
    SELECT OBJECT_NAME(object_id) AS table_name,
       SUM(row_count) AS [rows],
       CAST(SUM(used_page_count)*8.0/1024 AS decimal(12,2)) AS used_mb
    FROM sys.dm_db_partition_stats
    WHERE OBJECT_NAME(object_id) IN ('Vehicle_Inspection_staging', 'Vehicle_Inspection_clean')
    GROUP BY object_id
    ORDER BY used_mb;


    --------------------------------------------------------------------------------------

     WITH CTE AS 
     (SELECT
     OBJECT_NAME(object_id) AS table_name,
       SUM(row_count) AS [rows],
       CAST(SUM(used_page_count)*8.0/1024 AS decimal(12,2)) AS used_mb
    FROM sys.dm_db_partition_stats
    WHERE OBJECT_NAME(object_id) LIKE '%_CLEAN'  
    GROUP BY object_id)
    SELECT SUM(used_mb)
    FROM CTE 

    









































